####
POST http://localhost:4000/registrations-api/register
Content-Type: application/json

{
    "address" :  "mani",
    "city" : "mani",
    "name" : "mani",
    "pincode" : "mani",
    "state" : "mani"
}

####
GET http://localhost:4000/registrations-api/get-hospital/Jangaon/GANGISHETTYMANIDEEP

####
POST http://localhost:4000/ratings-api/post-rating/Jangaon/GANGISHETTYMANIDEEP
Content-Type: application/json

{
    "doctors": 4,
    "infra": 3,
    "equip": 4,
    "medication": 5,
    "services": 4
}
